name: Build PhantomJS Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"

env:
  FORCE_COLOR: 3

concurrency:
  group: github.workflowâˆ’{{ github.workflow }}-{{ github.ref }}
  cancel-in-progress: true


jobs:
  build_wheels:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os_arch: 
          - "linux_64bit"
          - "linux_32bit"
          - "windows_64bit"
          - "darwin_64bit"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip & install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Set TARGET_OS and TARGET_ARCH
        run: |
          case "${{ matrix.os_arch }}" in
            linux_64bit)
              echo "TARGET_OS=linux" >> $GITHUB_ENV
              echo "TARGET_ARCH=64bit" >> $GITHUB_ENV
              ;;
            linux_32bit)
              echo "TARGET_OS=linux" >> $GITHUB_ENV
              echo "TARGET_ARCH=32bit" >> $GITHUB_ENV
              ;;
            windows_64bit)
              echo "TARGET_OS=windows" >> $GITHUB_ENV
              echo "TARGET_ARCH=64bit" >> $GITHUB_ENV
              ;;
            darwin_64bit)
              echo "TARGET_OS=darwin" >> $GITHUB_ENV
              echo "TARGET_ARCH=64bit" >> $GITHUB_ENV
              ;;
          esac

      - name: Build wheel (download driver)
        run: python setup.py bdist_wheel

      - name: List built wheel
        run: ls -lR .

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os_arch }}
          path: dist/*.whl
          overwrite: false


  release:
    name: Release Assets and Upload to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest

    steps:
      # Determine release type
      - name: Determine release type
        id: release_type
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/v.*$ ]]; then
            echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "IS_TAG=true" >> $GITHUB_ENV
          else
            echo "RELEASE_NAME=__beta__" >> $GITHUB_ENV
            echo "IS_TAG=false" >> $GITHUB_ENV
          fi
        shell: bash # Use bash for all platforms
        
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

  
      - name: List dist directory
        run: tree --du -shaC . # Ensure the directory is not empty

      - name: Create or update release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: ${{ env.IS_TAG == 'false' }}
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishing to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{ secrets.PYPI_PASS }}
          user: ${{ secrets.PYPI_USER }}